---
- name: Manage 7-Zip Status
  ansible.windows.win_package:
    path: https://www.7-zip.org/a/7z2401-x64.msi
    product_id: '{23170F69-40C1-2702-2401-000001000000}'
    # We use a variable here instead of hardcoding 'present'
    state: "{{ app_state | default('present') }}"
 register: sevenzip_result
