---
- name: Manage 7-Zip Status
  ansible.windows.win_package:
    path: https://www.7-zip.org/a/7z2401-x64.msi
    product_id: '{23170F69-40C1-2702-2401-000001000000}'
    # We use a variable here instead of hardcoding 'present'
    state: "{{ app_state | default('present') }}"
 register: sevenzip_result
- name: Reboot immediately after 7-Zip change
  ansible.windows.win_reboot:
    msg: "Test Server: Rebooting immediately due to 7-Zip {{ app_state | default('present') }}"
    reboot_timeout: 600
  # This triggers ONLY if 7-Zip was added or removed
  when: sevenzip_result.changed
